/**
 * Seeds para itens de menu
 */

const menuItems = [
  // Itens principais
  {
    titulo: 'Dashboard',
    descricao: 'Painel principal com visão geral do sistema',
    icone: 'dashboard',
    url: '/',
    componente: 'Dashboard',
    ordem: 1,
    ativo: true,
    externo: false,
    requer_auth: true,
    nivel_min: 1,
    permissoes: null,
  },
  {
    titulo: 'Equipamentos',
    descricao: 'Gestão de equipamentos',
    icone: 'computer',
    url: '/equipamentos',
    componente: 'Equipamentos',
    ordem: 2,
    ativo: true,
    externo: false,
    requer_auth: true,
    nivel_min: 1,
    permissoes: null,
  },
  {
    titulo: 'Departamentos',
    descricao: 'Gestão de departamentos',
    icone: 'business',
    url: '/departamentos',
    componente: 'Departamentos',
    ordem: 3,
    ativo: true,
    externo: false,
    requer_auth: true,
    nivel_min: 2,
    permissoes: null,
  },
  {
    titulo: 'Usuários',
    descricao: 'Gestão de usuários',
    icone: 'people',
    url: '/usuarios',
    componente: 'Usuarios',
    ordem: 4,
    ativo: true,
    externo: false,
    requer_auth: true,
    nivel_min: 3,
    permissoes: 'usuarios.ler',
  },
  {
    titulo: 'Relatórios',
    descricao: 'Relatórios e análises',
    icone: 'assessment',
    url: '/relatorios',
    componente: 'Relatorios',
    ordem: 5,
    ativo: true,
    externo: false,
    requer_auth: true,
    nivel_min: 2,
    permissoes: 'relatorios.gerar',
  },
  {
    titulo: 'Configurações',
    descricao: 'Configurações do sistema',
    icone: 'settings',
    url: '/configuracoes',
    componente: 'Configuracoes',
    ordem: 6,
    ativo: true,
    externo: false,
    requer_auth: true,
    nivel_min: 4,
    permissoes: 'configuracoes.ler',
  },
  
  // Subitens de Equipamentos
  {
    titulo: 'Todos os Equipamentos',
    descricao: 'Listar todos os equipamentos',
    icone: 'list',
    url: '/equipamentos/listar',
    componente: 'ListaEquipamentos',
    ordem: 1,
    ativo: true,
    externo: false,
    requer_auth: true,
    nivel_min: 1,
    permissoes: 'equipamentos.ler',
    pai_titulo: 'Equipamentos',
  },
  {
    titulo: 'Novo Equipamento',
    descricao: 'Cadastrar novo equipamento',
    icone: 'add_circle',
    url: '/equipamentos/novo',
    componente: 'NovoEquipamento',
    ordem: 2,
    ativo: true,
    externo: false,
    requer_auth: true,
    nivel_min: 2,
    permissoes: 'equipamentos.criar',
    pai_titulo: 'Equipamentos',
  },
  {
    titulo: 'Tipos de Equipamento',
    descricao: 'Gerenciar tipos de equipamento',
    icone: 'category',
    url: '/equipamentos/tipos',
    componente: 'TiposEquipamento',
    ordem: 3,
    ativo: true,
    externo: false,
    requer_auth: true,
    nivel_min: 3,
    permissoes: 'equipamentos.ler',
    pai_titulo: 'Equipamentos',
  },
  {
    titulo: 'Status de Equipamento',
    descricao: 'Gerenciar status de equipamento',
    icone: 'check_circle',
    url: '/equipamentos/status',
    componente: 'StatusEquipamento',
    ordem: 4,
    ativo: true,
    externo: false,
    requer_auth: true,
    nivel_min: 3,
    permissoes: 'equipamentos.ler',
    pai_titulo: 'Equipamentos',
  },
  
  // Subitens de Configurações
  {
    titulo: 'Geral',
    descricao: 'Configurações gerais do sistema',
    icone: 'tune',
    url: '/configuracoes/geral',
    componente: 'ConfiguracoesGerais',
    ordem: 1,
    ativo: true,
    externo: false,
    requer_auth: true,
    nivel_min: 4,
    permissoes: 'configuracoes.ler',
    pai_titulo: 'Configurações',
  },
  {
    titulo: 'Personalização',
    descricao: 'Personalização de tema e aparência',
    icone: 'palette',
    url: '/configuracoes/personalizacao',
    componente: 'ConfiguracoesPersonalizacao',
    ordem: 2,
    ativo: true,
    externo: false,
    requer_auth: true,
    nivel_min: 4,
    permissoes: 'temas.ler',
    pai_titulo: 'Configurações',
  },
  {
    titulo: 'Menu',
    descricao: 'Configurações de menu',
    icone: 'menu_open',
    url: '/configuracoes/menu',
    componente: 'ConfiguracoesMenu',
    ordem: 3,
    ativo: true,
    externo: false,
    requer_auth: true,
    nivel_min: 4,
    permissoes: 'menu.ler',
    pai_titulo: 'Configurações',
  },
  {
    titulo: 'Logs de Auditoria',
    descricao: 'Visualização de logs de auditoria',
    icone: 'history',
    url: '/configuracoes/auditoria',
    componente: 'ConfiguracoesAuditoria',
    ordem: 4,
    ativo: true,
    externo: false,
    requer_auth: true,
    nivel_min: 4,
    permissoes: 'auditoria.ler',
    pai_titulo: 'Configurações',
  },
];

async function seedMenuItems(prisma) {
  console.log('Criando itens de menu...');
  
  // Primeiro, criamos todos os itens de menu principais (sem pai)
  const menuPrincipais = {};
  for (const item of menuItems.filter(item => !item.pai_titulo)) {
    const menuItem = await prisma.menuItem.upsert({
      where: { id: item.id || 0 },
      update: {
        titulo: item.titulo,
        descricao: item.descricao,
        icone: item.icone,
        url: item.url,
        componente: item.componente,
        ordem: item.ordem,
        ativo: item.ativo,
        externo: item.externo,
        requer_auth: item.requer_auth,
        nivel_min: item.nivel_min,
        permissoes: item.permissoes,
      },
      create: {
        titulo: item.titulo,
        descricao: item.descricao,
        icone: item.icone,
        url: item.url,
        componente: item.componente,
        ordem: item.ordem,
        ativo: item.ativo,
        externo: item.externo,
        requer_auth: item.requer_auth,
        nivel_min: item.nivel_min,
        permissoes: item.permissoes,
      },
    });
    menuPrincipais[item.titulo] = menuItem;
  }
  
  // Depois, criamos os subitens com referência aos pais
  for (const item of menuItems.filter(item => item.pai_titulo)) {
    const pai = menuPrincipais[item.pai_titulo];
    if (pai) {
      await prisma.menuItem.upsert({
        where: { id: item.id || 0 },
        update: {
          titulo: item.titulo,
          descricao: item.descricao,
          icone: item.icone,
          url: item.url,
          componente: item.componente,
          ordem: item.ordem,
          ativo: item.ativo,
          externo: item.externo,
          requer_auth: item.requer_auth,
          nivel_min: item.nivel_min,
          permissoes: item.permissoes,
          pai_id: pai.id,
        },
        create: {
          titulo: item.titulo,
          descricao: item.descricao,
          icone: item.icone,
          url: item.url,
          componente: item.componente,
          ordem: item.ordem,
          ativo: item.ativo,
          externo: item.externo,
          requer_auth: item.requer_auth,
          nivel_min: item.nivel_min,
          permissoes: item.permissoes,
          pai_id: pai.id,
        },
      });
    }
  }
  
  console.log('Itens de menu criados com sucesso!');
}

module.exports = { seedMenuItems };
